---
title: Intershore Companies
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Onshore and offshore companies for digital nomads and entrepreneurs
github_repo: companies
github_username: intershore
theme_color: light
remote_theme: broccolini/athena
permalink: pretty
markdown: kramdown
